# Generated by Django 6.0.4 on 2026-04-25 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва приміщення')),
                ('capacity', models.IntegerField(verbose_name='Місткість')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Приміщення',
                'verbose_name_plural': 'Приміщення',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200, verbose_name="Ім'я гостя")),
                ('check_in_date', models.DateTimeField(verbose_name='Дата заїзду')),
                ('check_out_date', models.DateTimeField(verbose_name='Дата виїзду')),
                ('status', models.CharField(choices=[('pending', 'Очікується'), ('checked_in', 'Заїхав'), ('checked_out', 'Виїхав'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('actual_check_in', models.DateTimeField(blank=True, null=True, verbose_name='Фактичний заїзд')),
                ('actual_check_out', models.DateTimeField(blank=True, null=True, verbose_name='Фактичний виїзд')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concierge.room', verbose_name='Приміщення')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
            },
        ),
    ]
